// Lucide 描边图标，笔画粗细走 CSS 变量
// 非 jp-pixel 字体才显示；jp-pixel 那边用 pixel-icons 块面版
import type { IconNode } from 'lucide';
import {
  BarChart3,
  Binary,
  BookOpen,
  Brain,
  Calculator,
  Calendar,
  CheckSquare,
  Circle,
  Clock,
  Cloud,
  CloudFog,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CloudSun,
  Code,
  Coffee,
  Eraser,
  FileText,
  Folder,
  FolderOpen,
  Frame,
  FunctionSquare,
  Globe,
  LayoutGrid,
  Link,
  List,
  Map,
  Monitor,
  Moon,
  Mountain,
  Music,
  Network,
  NotebookText,
  Orbit,
  Palette,
  PenLine,
  Presentation,
  Puzzle,
  Radio,
  Search,
  Settings,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Thermometer,
  Timer,
  TrendingUp,
  Waves,
} from 'lucide';
import type { PixelIconName } from './pixel-icons';

export type UiIconNode = IconNode;

const UI_ICONS: Record<PixelIconName, readonly UiIconNode[]> = {
  notes: NotebookText,
  folder: Folder,
  'folder-open': FolderOpen,
  note: FileText,
  terminal: Terminal,
  chart: BarChart3,
  brain: Brain,
  cup: Coffee,
  spark: Sparkles,
  map: Map,
  orbit: Orbit,
  arc: TrendingUp,
  ring: Circle,
  grid: LayoutGrid,
  gear: Settings,
  puzzle: Puzzle,
  frame: Frame,
  monitor: Monitor,
  landscape: Mountain,
  clock: Clock,
  music: Music,
  book: BookOpen,
  check: CheckSquare,
  calendar: Calendar,
  timer: Timer,
  cloud: Cloud,
  sun: Sun,
  moon: Moon,
  'cloud-sun': CloudSun,
  'cloud-moon': CloudMoon,
  rain: CloudRain,
  snow: CloudSnow,
  fog: CloudFog,
  storm: CloudLightning,
  thermo: Thermometer,
  globe: Globe,
  signal: Radio,
  graph: Network,
  calc: Calculator,
  code: Code,
  pen: PenLine,
  search: Search,
  star: Star,
  link: Link,
  island: Waves,
  clear: Eraser,
  python: Code,
  matlab: FunctionSquare,
  digits: Binary,
  whiteboard: Presentation,
  list: List,
  palette: Palette,
};

export function getUiIconNodes(name: PixelIconName): readonly UiIconNode[] {
  return UI_ICONS[name] ?? UI_ICONS.note;
}

// Lucide 节点拆成 tag + attrs，方便 Svelte / Astro 里拼
export function uiIconNodeProps(node: UiIconNode): { tag: string; attrs: Record<string, string | number> } {
  const [tag, attrs] = node;
  return { tag, attrs: attrs as Record<string, string | number> };
}
