import type { PartDef } from './helpers';
import { L, lesson } from './helpers';

export const CURRICULUM_PARTS_6_10: PartDef[] = [
  {
    id: 'sketching',
    title: '第六部分：Curve Sketching 曲线草图',
    topics: [
      { id: 'sk-domain', title: '定义域', steps: [L('第一步', '先写定义域，标垂直渐近线候选点。')] },
      { id: 'sk-intercepts', title: 'x、y 截距', steps: [L('x 截距', '令 y=0 解 x。'), L('y 截距', '令 x=0 求 y（若在定义域内）。')] },
      { id: 'sk-symmetry', title: '对称性', steps: [L('奇偶', '判断奇/偶函数；周期函数找周期。')] },
      { id: 'sk-vasymptote', title: '垂直渐近线', steps: [L('方法', 'x→a 时 |f|→∞ 的分母零点（未消去）。')] },
      { id: 'sk-hasymptote', title: '水平渐近线', steps: [L('方法', 'x→±∞ 时 f(x) 的极限。')] },
      { id: 'sk-sasymptote', title: '斜渐近线', steps: [L('方法', 'lim [f(x)-(kx+b)]=0 求 k,b。')] },
      { id: 'sk-monotone', title: "f'(x) 单调性", steps: [L("f'>0", '递增；f\'<0 递减。')] },
      { id: 'sk-extrema', title: '临界点与极值', steps: [L('临界点', "f'=0 或 f' 不存在。"), L('极值', '一阶/二阶判别。')] },
      { id: 'sk-concavity', title: "f''(x) 凹凸性", steps: [L("f''>0", '凹向上；f\'\'<0 凹向下。')] },
      { id: 'sk-inflection', title: '拐点', steps: [L('拐点', "f'' 变号的点。")] },
      { id: 'sk-endpoints', title: '端点行为', steps: [L('端点', '区间端点函数值与极限。')] },
      { id: 'sk-full', title: '综合画图', steps: [L('汇总', '按顺序标出所有信息，平滑连接。')] },
    ],
  },
  {
    id: 'taylor',
    title: '第七部分：Taylor Series 泰勒级数',
    topics: [
      {
        id: 'taylor-formula',
        title: 'Taylor 多项式公式',
        interactive: 'taylor',
        steps: [
          L('公式', 'T_n(x)=Σ f^{(k)}(a)/k! · (x-a)^k。', 'T_n(x)=\\sum_{k=0}^{n}\\frac{f^{(k)}(a)}{k!}(x-a)^k'),
        ],
      },
      { id: 'maclaurin', title: 'Maclaurin Series (a=0)', steps: [L('特例', 'a=0 时的 Taylor 级数。')] },
      { id: 'series-expx', title: 'e^x 展开', steps: [L('级数', 'e^x=Σ x^n/n!。', 'e^x=\\sum_{n=0}^{\\infty}\\frac{x^n}{n!}')] },
      { id: 'series-sinx', title: 'sin x 展开', steps: [L('级数', 'sin x=Σ (-1)^n x^{2n+1}/(2n+1)!。')] },
      { id: 'series-cosx', title: 'cos x 展开', steps: [L('级数', 'cos x=Σ (-1)^n x^{2n}/(2n)!。')] },
      { id: 'series-geom', title: '1/(1-x) 几何级数', steps: [L('级数', '1/(1-x)=Σ x^n, |x|<1。', '\\frac{1}{1-x}=\\sum_{n=0}^{\\infty}x^n')] },
      { id: 'series-ln', title: 'ln(1+x) 展开', steps: [L('级数', 'ln(1+x)=Σ (-1)^{n+1} x^n/n, |x|≤1。')] },
      { id: 'series-binomial', title: '(1+x)^k 二项级数', steps: [L('级数', '广义二项式系数 C(k,n)。')] },
      { id: 'series-substitute', title: '代换法构造新级数', steps: [L('代换', '将 x 换为 -x² 等得到新级数。')] },
      { id: 'series-ops', title: '求导/积分构造新级数', steps: [L('逐项', '在收敛区间内逐项求导或积分。')] },
      { id: 'lagrange-remainder', title: 'Lagrange 余项与误差', steps: [L('余项', 'R_n(x)=f^{(n+1)}(ξ)/(n+1)! · (x-a)^{n+1}。')] },
      { id: 'radius', title: '收敛半径', steps: [L('比值/根值', '用比值判别法或根值判别法求 R。')] },
    ],
  },
  {
    id: 'integration-basic',
    title: '第八部分：Integration 积分基础',
    topics: [
      { id: 'ftc1', title: 'FTC 第一部分（变限积分求导）', steps: [L('公式', 'd/dx ∫_a^x f(t)dt = f(x)。', '\\frac{d}{dx}\\int_a^x f(t)\\,dt=f(x)')] },
      { id: 'ftc1-chain', title: 'FTC + Chain Rule', steps: [L('上限 g(x)', 'd/dx ∫_a^{g(x)} f = f(g(x))·g\'(x)。')] },
      { id: 'ftc1-double', title: 'FTC 双变限', steps: [L('双变限', 'd/dx ∫_{u(x)}^{v(x)} f = f(v)v\' − f(u)u\'。')] },
      { id: 'ftc2', title: 'FTC 第二部分', steps: [L('公式', '∫_a^b f(x)dx = F(b)−F(a)。', '\\int_a^b f=F(b)-F(a)')] },
      { id: 'usub-indef', title: 'u-substitution 不定积分', steps: [L('模板', '∫ f(g(x))g\'(x)dx = ∫ f(u)du。')] },
      { id: 'usub-def', title: 'u-substitution 定积分', steps: [L('换限', '定积分换元必须同时换上下限！')] },
      { id: 'usub-patterns', title: '常见 substitution 模式', steps: [L('识别', '括号内、根号下、分母、指数、对数内。')] },
    ],
  },
  {
    id: 'riemann',
    title: '第九部分：Riemann Sums 黎曼和',
    topics: [
      {
        id: 'riemann-dx',
        title: 'Δx = (b−a)/n',
        interactive: 'integral',
        steps: [L('步长', '区间等分，Δx=(b−a)/n。', '\\Delta x=\\frac{b-a}{n}')],
      },
      { id: 'left-sum', title: 'Left Riemann Sum', steps: [L('左端点', '每小区间取左端点函数值。')] },
      { id: 'right-sum', title: 'Right Riemann Sum', steps: [L('右端点', '每小区间取右端点函数值。')] },
      { id: 'mid-sum', title: 'Midpoint Riemann Sum', steps: [L('中点', '取中点函数值，通常更准。')] },
      { id: 'inc-bound', title: '递增函数：Left 下界、Right 上界', steps: [L('单调', '递增时左和小于积分，右和大于积分。')] },
      { id: 'dec-bound', title: '递减函数：Right 下界、Left 上界', steps: [L('单调', '递减时相反。')] },
      { id: 'mid-accuracy', title: '精度比较（Midpoint 最准）', steps: [L('比较', '同样 n 下中点法误差通常更小。')] },
    ],
  },
  {
    id: 'integration-advanced',
    title: '第十部分：单变量积分进阶',
    topics: [
      { id: 'int-plus-c', title: '不定积分 +C，定积分不加', steps: [L('规则', '不定积分必须加常数 C；定积分是数值。')] },
      { id: 'int-linear', title: '线性性质', steps: [L('性质', '∫(af+bg)=a∫f+b∫g。')] },
      { id: 'int-power', title: '幂函数积分', steps: [L('公式', '∫x^n dx = x^{n+1}/(n+1)+C, n≠−1。')] },
      { id: 'int-1overx', title: '∫1/x dx = ln|x|+C', steps: [L('绝对值', '别忘 |x|！')] },
      { id: 'int-exp', title: '∫e^x, ∫a^x', steps: [L('公式', '∫e^x=e^x+C；∫a^x=a^x/ln a+C。')] },
      { id: 'int-trig', title: '6 个三角函数积分', steps: [L('基本', '∫sin=−cos, ∫cos=sin, ∫sec²=tan 等。')] },
      { id: 'int-tan-sec', title: '∫tan x, ∫sec x', steps: [L('公式', '∫tan=−ln|cos|; ∫sec=ln|sec+tan|。')] },
      { id: 'int-inverse-trig', title: '反三角积分', steps: [L('公式', '∫1/√(1−x²)=arcsin; ∫1/(1+x²)=arctan。')] },
      { id: 'int-def-props', title: '定积分 5 条性质', steps: [L('性质', '线性、区间可加、反向变号、比较、中值定理。')] },
      { id: 'int-even-odd', title: '奇偶对称区间', steps: [L('对称', '奇函数：∫_{−a}^a=0；偶函数：2∫_0^a。')] },
      { id: 'usub-5steps', title: 'u-substitution 5 步流程', steps: lesson('换元五步法', [['选 u', '找内层函数'], ['求 du', 'du=u\'dx'], ['代换', '化为 ∫f(u)du'], ['积分', '求原函数'], ['回代', 'u=g(x)']]) },
      { id: 'ibp', title: '分部积分', steps: [L('公式', '∫u dv = uv − ∫v du。', '\\int u\\,dv=uv-\\int v\\,du')] },
      { id: 'iate', title: 'LIATE 口诀', steps: [L('顺序', 'Log, Inverse trig, Algebraic, Trig, Exp — 优先选 u。')] },
      { id: 'int-lnx', title: '∫ln x dx 技巧', steps: [L('分部', 'u=ln x, dv=dx。', '\\int\\ln x\\,dx=x\\ln x-x+C')] },
      { id: 'ibp-repeat', title: '重复分部积分', steps: [L('重复', '如 ∫x²e^x 需两次分部。')] },
      { id: 'ibp-cycle', title: '循环型分部积分', steps: [L('循环', '∫e^x sin x dx 设 I 解方程。')] },
      { id: 'trig-sub-1', title: '三角换元 √(a²−x²)', steps: [L('换元', 'x=a sin θ。')] },
      { id: 'trig-sub-2', title: '三角换元 √(a²+x²)', steps: [L('换元', 'x=a tan θ。')] },
      { id: 'trig-sub-3', title: '三角换元 √(x²−a²)', steps: [L('换元', 'x=a sec θ。')] },
      { id: 'partial-frac', title: '部分分式分解', steps: [L('分解', '有理函数拆成简单分式之和。')] },
      { id: 'improper-1', title: '反常积分类型 I（无穷区间）', steps: [L('定义', '∫_a^∞ f = lim_{t→∞} ∫_a^t f。')] },
      { id: 'improper-2', title: '反常积分类型 II（无界被积点）', steps: [L('定义', '在奇点处用极限定义。')] },
      { id: 'improper-converge', title: '收敛 vs 发散', steps: [L('判断', '极限存在且有限则收敛。')] },
      { id: 'p-test', title: 'p-test', steps: [L('p 积分', '∫_1^∞ 1/x^p 当 p>1 收敛。')] },
      { id: 'area-between', title: '两曲线面积', steps: [L('公式', '∫_a^b [f−g]dx，f 在上。', 'A=\\int_a^b[f(x)-g(x)]\\,dx')] },
      { id: 'disk-method', title: '圆盘法（绕 x 轴）', steps: [L('体积', 'V=π∫[f(x)]²dx。', 'V=\\pi\\int_a^b[f(x)]^2\\,dx')] },
      { id: 'washer-method', title: '圆环法体积', steps: [L('体积', 'V=π∫([R]²−[r]²)dx。')] },
      { id: 'shell-method', title: '柱壳法（绕 y 轴）', steps: [L('体积', 'V=2π∫x·f(x)dx。', 'V=2\\pi\\int_a^b x f(x)\\,dx')] },
      { id: 'arc-length', title: '弧长公式', steps: [L('公式', 'L=∫√(1+(dy/dx)²)dx。', 'L=\\int_a^b\\sqrt{1+(y\')^2}\\,dx')] },
      { id: 'avg-value', title: '函数平均值', steps: [L('公式', 'f_avg = (1/(b−a))∫_a^b f(x)dx。')] },
    ],
  },
  {
    id: 'pitfalls',
    title: '⚠️ 高频易错点',
    topics: [
      { id: 'err-plus-c', title: '不定积分忘记 +C', steps: [L('提醒', '不定积分结果必须 +C。')] },
      { id: 'err-usub-limits', title: '定积分换元没改上下限', steps: [L('提醒', '换 u 后上下限也要换，或回代 x。')] },
      { id: 'err-ln-abs', title: '∫1/x 漏写绝对值', steps: [L('提醒', '∫1/x dx = ln|x|+C。')] },
      { id: 'err-exp-coeff', title: '∫e^{2x}dx 忘除以 2', steps: [L('提醒', '∫e^{kx}dx = (1/k)e^{kx}+C。', '\\int e^{2x}dx=\\tfrac12 e^{2x}+C')] },
      { id: 'err-pi-volume', title: '体积公式漏 π', steps: [L('提醒', '圆盘/圆环/柱壳公式含 π。')] },
      { id: 'err-lhopital', title: '洛必达没验证不定式', steps: [L('提醒', '先确认 0/0 或 ∞/∞。')] },
      { id: 'err-quotient', title: 'Quotient Rule 分子符号', steps: [L('提醒', "分子 u'v − uv'，减号顺序。")] },
      { id: 'err-chain', title: 'Chain Rule 少乘内层导数', steps: [L('提醒', '复合函数务必链式。')] },
      { id: 'err-implicit', title: '隐函数求导漏 dy/dx', steps: [L('提醒', '对 y 项求导要乘 y\'。')] },
      { id: 'err-opt-verify', title: 'Optimization 只算临界点', steps: [L('提醒', '比较端点与临界点，验证最值。')] },
    ],
  },
];
